### DISCUSSION TITLE
Identity Hub EDC_IH_API_SUPERUSER_KEY env not working

### DISCUSSION THREAD

**Discussion by MartinFerenec** [eclipse-edc/IdentityHub#452] [Q&A]
Does anyone know how to authenticate Identity Hub - Identity API with `super-user`?

I have followed:
* https://github.com/eclipse-edc/IdentityHub/blob/main/docs/developer/architecture/identity-api.security.md
* https://github.com/eclipse-edc/IdentityHub/pull/256 

 This is my `docker-compose.yml` located in the root directory of repo:
```yml
version: '3.9'

services:
  edc-identity-hub:
    build:
      context: ./launcher
    image: identity-hub:latest
    container_name: edc-identity-hub
    environment:
      - WEB_HTTP_PRESENTATION_PORT=10001
      - WEB_HTTP_PRESENTATION_PATH=/api/presentation/
      - WEB_HTTP_PATH=/api
      - WEB_HTTP_PORT=8181
      - WEB_HTTP_IDENTITY_PORT=8182
      - WEB_HTTP_IDENTITY_PATH=/api/identity
      - EDC_IH_API_SUPERUSER_KEY=c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo=
    ports:
      - "8181:8181"
      - "8182:8182"
      - "10001:10001"
    restart: no
    networks:
      - eclipse-edc

networks:
  eclipse-edc:
```

And the `EDC_IH_API_SUPERUSER_KEY` env is what I use in header `x-api-key`:

![image](https://github.com/user-attachments/assets/01e1f8dd-093b-4c37-8856-48c24b23c280)
